import { Inter } from "next/font/google";
import Link from "next/link";
import 'bootstrap/dist/css/bootstrap.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>App prueba</title>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" />
      </head>
      <body className={inter.className}>
      <header style={{ position: 'fixed', top: 0, right: 0, left: 0, zIndex: 1030 }}>
          </header>
        {children}
        </body>
    </html>
  );
}